### ISSUE TITLE
Feature request: SPI

### ISSUE THREAD

**Issue by gergoerdi** [Patryk27/avr-tester#1]
Probably could be similar to existing UART support.

**Comment by Patryk27** [comment]
Yes, it should be relatively straightforward to implement - I see you've prepared some commit, which looks pretty neat; would you like to create a pull request with it? 🙂

**Comment by gergoerdi** [comment]
> I see you've prepared some commit which looks pretty neat - would you like to create a pull request with it?

Unfortunately, my branch doesn't work yet...

**Comment by Patryk27** [comment]
Sure, in this case I'll try to come up with something over the week - I'll ping you on the pull request, if you'd like to try the code once it's ready 🙂

**Comment by Patryk27** [comment]
> Unfortunately, my branch doesn't work yet...

You were pretty close, though!

In simavr, SPIs are ordered with numbers, not characters, so while UART is identified with `'0'` or `'1'`, SPIs are identifier with `0` or `1`, i.e.:

```rust
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum IoCtl {
    /* ... */
    SpiGetIrq { spi: u8 }, // note the u8 here
    /* ... */
}

impl IoCtl {
    pub fn into_ffi(self) -> u32 {
        let ctl = match self {
            /* ... */
            IoCtl::SpiGetIrq { spi } => [b's', b'p', b'i', spi],
            /* ... */
        };

        /* ... */
    }
}
```

Seizing the day I want to refactor w few things, but it looks like the feature is mostly working this way 🙂

**Comment by Patryk27** [comment]
> Unfortunately, my branch doesn't work yet...

You were pretty close, though!

In simavr, SPIs are ordered with numbers, not characters, so while UART is identified with `'0'` or `'1'`, SPIs are identified with `0` or `1`, i.e.:

```rust
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum IoCtl {
    /* ... */
    SpiGetIrq { spi: u8 }, // note the u8 here
    /* ... */
}

impl IoCtl {
    pub fn into_ffi(self) -> u32 {
        let ctl = match self {
            /* ... */
            IoCtl::SpiGetIrq { spi } => [b's', b'p', b'i', spi],
            /* ... */
        };

        /* ... */
    }
}
```

Seizing the day I want to refactor w few things, but it looks like the feature is mostly working this way 🙂

**Comment by gergoerdi** [comment]
> You were pretty close, though!
> 
> In simavr, SPIs are ordered with numbers, not characters, so while UART is identified with `'0'` or `'1'`, SPIs are identified with `0` or `1`

Ah, I would have never in a million years...

Thanks for looking into this.

**Comment by gergoerdi** [comment]
Can you add an example `component` that responds to SPI MOSI with some MISO reply depending on the value of some other (chip select-like) pins?

**Comment by Patryk27** [comment]
Sure, I'll come up with something 🙂
