### ISSUE TITLE
UART starts buffering only after first read?

### ISSUE THREAD

**Issue by nilclass** [Patryk27/avr-tester#3]
This is what I experienced: I had a call to `avr.uart0().read::<String>()` in a test, but the call happened only after a bit of other code ran. The effect was that the output read was incomplete.
At first I thought the buffer size was limited, but then I realized that I was only seeing output that was generated after the first bit of code had finished, and everything works correctly when I added `avr.uart0().try_read_byte()` before the first call to `avr.run()`.

So, it seems to me that the buffer is only filled after `uart0` is first used.

Is this by design or by accident? If it's by design, probably good to document it.

I love this project btw, great work!

**Comment by Patryk27** [comment]
Yeah, something's off here - it's by accident :smile:
I'll try to debug this thingie and we'll see.

**Comment by Patryk27** [comment]
I've released 0.2.1 with the fix (and your pull request); thanks for reporting 🙂
